package_manager: yay # or "paru"
pentest_setup: true
update_mirrorlist: false
git:
  user: ""
  email: ""
systemd_services:
  - vmtoolsd # VMware Tools
  - vmware-vmblock-fuse # VMware Tools
  - docker # Docker
packages:
  general:
    - ulauncher # Ulauncher
    - imwheel # Mouse wheel acceleration
    - openvpn # VPN
    - keybase-bin # Keybase
    - open-vm-tools # VMware Tools
    - nerd-fonts-jetbrains-mono # Nerd Fonts
    - git # Git
    - zsh # Terminal shell (Zsh)
    - kitty # Terminal emulator (Kitty)
    - neovim # Text editor (Neovim)
    - bat # Cat clone with syntax highlighting and Git integration
    - ripgrep # Line-oriented search tool that recursively searches your current directory for a regex pattern
    - fd # Simple, fast and user-friendly alternative to find
    - lsd # The next gen ls command (ls replacement)
    - grc # Colourize logfiles and command output
    - ncdu # Disk usage analyzer with an ncurses interface
    - papirus-icon-theme # Papirus icon theme
    - thefuck # Magnificent app which corrects your previous console command
    - rustup # Rust toolchain installer
    - visual-studio-code-bin # Visual Studio Code
    - docker # Docker
    - texlive-core # TeX Live
    - latex-mk # LaTeX build tool
    - flameshot # Screenshot tool
    - xdotool # Command-line X11 automation tool
    - xclip # Command line interface to the X11 clipboard
    - xsel # Command-line program for getting and setting the contents of the X selection
    - xorg-xset # X.Org X server settings program
    - wmctrl # Command line tool to interact with an EWMH/NetWM compatible X Window Manager
    - ghcup-hs-bin # Haskell toolchain installer
    - cabal-install # Haskell build tool
    - stack # Haskell build tool
    - ncurses5-compat-libs # Compatibility libraries for ncurses 5
  pentest_tools:
    - nmap # Network exploration tool and security / port scanner
    - vulscan # Nmap NSE script for vulnerability scanning
    - metasploit # Penetration testing framework
    - wordlists # Wordlists for password cracking and other security testing
    - burpsuite # Web application security testing tool
    - burpsuite-pro # Burp Suite Professional
    - sqlmap # Automatic SQL injection and database takeover tool
    - gobuster # Directory/file, DNS and virtual host busting tool written in Go
    - dirb # Web Content Scanner
    - dirbuster # Web Content Scanner
    - nikto # Web server scanner which performs comprehensive tests against web servers for multiple items, including over 6700 potentially dangerous files/programs
    - nessus # Vulnerability scanner
    - wpscan # WordPress vulnerability scanner
    - wireshark-qt # Network protocol analyzer
    - wireshark-cli # Network protocol analyzer
    - tcpdump # Network traffic analyzer
    - john # Password cracker
    - gnu-netcat # Networking utility which reads and writes data across networks from the command line
    - inetutils # Collection of common network programs
    - net-tools # Collection of common network tools
    - traceroute # Traces the route taken by packets over an IP network
    - iputils # Collection of small useful utilities for Linux networking
    - nessus # Vulnerability scanner
